        (function() {
            function getCookie(b){var f=b+"=";var a=document.cookie.split(";");for(var d=0;d<a.length;d++){var e=a[d];while(e.charAt(0)==" "){e=e.substring(1,e.length)}if(e.indexOf(f)==0){return e.substring(f.length,e.length)}}return null}
            var url = "https://www.trainghiemhay.com/";
            if(url && /ipod|iphone|ipad|android|symbianos|blackberry|webos|windows phone/i.test(navigator.userAgent)) {
                if (getCookie('mobile') != 0) {
                    location.href = url;
                    return;
                }
            }
            function setCookie(d,e,h,a,g){var f=d+"="+e;if(h){var b=new Date();b.setTime(b.getTime()+(h*24*60*60*1000));f+="; expires="+b.toGMTString()}f+="; path=/";if(a){f+="; domain="+a}if(g){f+="; secure"}document.cookie=f};
            window.nextByApkpure = function (u) {if(u){setCookie("apkpure__next", u, 300, 'trainghiemhay.com');}};
            Redirect={getLangCookie:function(){return getCookie("apkpure__lang")},setLangCookie:function(a){setCookie("apkpure__lang",a,300,"trainghiemhay.com")},isMainURL:function(){return Redirect.lang()==="en"&&'true'==="true"},lang:function(){return"vn"},isShowLangTip:false,langGoll:"",langGoUrl:"",prefix:"https://www.trainghiemhay.comm",getRedirectUrl: function (d) {return Redirect.prefix + "/" + d + "/"},isBetaLang:function(a){return[].indexOf(a)!==-1?true:false},getNavigatorLang:function(){return Redirect.translateLang(navigator.language)},translateLang:function(a){if(a=="en"||a.indexOf("en-")>=0){return"en"}else{if(a=="br"||a=="pt"||a.indexOf("pt-")>=0){return"br"}else{if(a=="zh-TW"){return"tw"}else{if(a=="cn"||a.indexOf("zh")>=0||a.indexOf("cn-")>=0||a.indexOf("zh-")>=0){return"cn"}else{if(a=="ar"||a.indexOf("ar-")>=0){return"ar"}else{if(a=="jp"||a.indexOf("jp-")>=0||a=="ja"||a.indexOf("ja-")>=0){return"jp"}else{if(a=="es"||a.indexOf("es-")>=0){return"es"}else{if(a=="ru"||a.indexOf("ru-")>=0){return"ru"}else{if(a=="in"||a.indexOf("in-")>=0){return"in"}else{if(a=="id"||a.indexOf("id-")>=0){return"id"}else{if(a=="it"||a.indexOf("it-")>=0){return"it"}else{if(a=="nl"||a.indexOf("nl-")>=0){return"nl"}else{if(a=="pl"||a.indexOf("pl-")>=0){return"pl"}else{if(a=='de'||a.indexOf('de-')>=0){return "de"}else{if(a=='vi'||a.indexOf('vi-')>=0){return "vn"}else{if(a=='fr'||a.indexOf('fr-') >=0){return "fr"}else{if(a=='tr'||a.indexOf('tr-') >=0){return "tr"}else{if(a=='ko'||a.indexOf('ko-') >=0){return "kr"}else{return "en"}}}}}}}}}}}}}}}}}}},check:function(){var b=Redirect.getLangCookie();if(!b){if(!Redirect.isMainURL()){Redirect.setLangCookie(Redirect.lang())}else{var a=Redirect.getNavigatorLang();if(Redirect.isBetaLang(a)){Redirect.isShowLangTip=true;Redirect.langGoll=a;Redirect.langGoUrl=Redirect.getRedirectUrl(a)}else{Redirect.setLangCookie(a);Redirect.run(Redirect.getLangCookie())}}}else{if(b==="menu"){Redirect.setLangCookie(Redirect.lang())}else{if(Redirect.isMainURL()){Redirect.run(b)}}}},run:function(a){if(a&&a!=="en"){location.href=Redirect.getRedirectUrl(a)}}};
            Redirect.check();
            window.policy_review = {effective:'20180525',isReview:function(){return getCookie("apkpure__policy_review") != policy_review.effective},setReview:function (){setCookie("apkpure__policy_review",policy_review.effective,300,"trainghiemhay.com");document.getElementById('policy-info').style.display='none'}};
        })();
